steps:
  # Build agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/${PROJECT_ID}/meeting-enjoyer-backend:latest', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/meeting-enjoyer-backend:latest']

  # Deploy agent service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'meeting-enjoyer-backend'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/meeting-enjoyer-backend:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

substitutions:
  _REGION: europe-west2

images:
  - 'gcr.io/${PROJECT_ID}/meeting-enjoyer-backend:latest' 